services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    networks:
      - uhbooba-net

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - uhbooba-net

  user-db:
    image: mariadb:latest
    container_name: user-db
    env_file:
      - .env.db
    ports:
      - "3307:3306"
    networks:
      - uhbooba-net
    volumes:
      - ./db/user:/var/lib/mariadb

  finance-db:
    image: mariadb:latest
    container_name: finance-db
    env_file:
      - .env.db
    ports:
      - "3308:3306"
    networks:
      - uhbooba-net
    volumes:
      - ./db/finance:/var/lib/mariadb

  external-db:
    image: mariadb:latest
    container_name: external-db
    env_file:
      - .env.db
    ports:
      - "3309:3306"
    networks:
      - uhbooba-net
    volumes:
      - ./db/external:/var/lib/mariadb

  eureka-server:
    container_name: eureka-server
    build:
      context: ./backend/eureka-server
    ports:
      - "8761:8761"
    networks:
      - uhbooba-net
    restart: on-failure

  user-service:
    container_name: user-service
    env_file:
      - .env.user
    build:
      context: ./backend/user-service
    ports:
      - "8081:8081"
    networks:
      - uhbooba-net
    restart: on-failure
    volumes:
      - ./logs/user-service:/app/logs
    depends_on:
      - eureka-server

  finance-service:
    container_name: finance-service
    env_file:
      - .env.finance
    build:
      context: ./backend/finance-service
    ports:
      - "8082:8082"
    networks:
      - uhbooba-net
    restart: on-failure
    volumes:
      - ./logs/finance-service:/app/logs
    depends_on:
      - eureka-server

  external-service:
    container_name: external-service
    env_file:
      - .env.external
    build:
      context: ./backend/external-service
    ports:
      - "8083:8083"
    networks:
      - uhbooba-net
    restart: on-failure
    volumes:
      - ./logs/external-service:/app/logs
    depends_on:
      - eureka-server

  api-gateway:
    container_name: api-gateway
    env_file:
      - .env.gateway
    build:
      context: ./backend/api-gateway
    ports:
      - "8080:8080"
    networks:
      - uhbooba-net
    restart: on-failure
    volumes:
      - ./logs/gateway-service:/app/logs
    depends_on:
      - eureka-server
      - user-service
      - finance-service
      - external-service

networks:
  uhbooba-net:
    driver: bridge