services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9070:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonarqube_db
    networks:
      - uhbooba-net

  sonarqube_db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    networks:
      - uhbooba-net

networks:
  uhbooba-net:
