services:
  zookeeper:
    image: bitnami/zookeeper:3.8.3
    container_name: uhbooba-zookeeper
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    expose:
      - "2181"
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    networks:
      - uhbooba-net

  kafka:
    image: bitnami/kafka:3.6
    container_name: uhbooba-kafka
    restart: unless-stopped
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=uhbooba-zookeeper:2181
      - KAFKA_CREATE_TOPICS="kafka_capstone_event_bus:1:1"
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://j11a402.p.ssafy.io:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - uhbooba-net

networks:
  uhbooba-net:

volumes:
  zookeeper-data:
  kafka-data:
