services:
  redis:
    image: redis:7.2.3
    container_name: uhbooba-redis
    networks:
      - uhbooba-net
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  user-db:
    image: mariadb:latest
    container_name: user-db
    env_file:
      - .env.db
    ports:
      - "3307:3306"
    networks:
      - uhbooba-net
    volumes:
      - user-db-data:/var/lib/mariadb

  finance-db:
    image: mariadb:latest
    container_name: finance-db
    env_file:
      - .env.db
    ports:
      - "3308:3306"
    networks:
      - uhbooba-net
    volumes:
      - finance-db-data:/var/lib/mariadb

  external-db:
    image: mariadb:latest
    container_name: external-db
    env_file:
      - .env.db
    ports:
      - "3309:3306"
    networks:
      - uhbooba-net
    volumes:
      - external-db-data:/var/lib/mariadb

networks:
  uhbooba-net:

volumes:
  user-db-data:
  finance-db-data:
  external-db-data:
